export type Data = {
  amount: string;
  curr: 'RON' | 'USD' | 'EUR';
  invoice_id: string;
  order_desc: string;
  merch_id: string;
  timestamp: string;
  nonce: string;
  fp_hash?: string;
  fname?: string;
  lname?: string;
  email?: string;
  redirect?: string;
  recurent?: 'Base';
  recurent_freq?: string;
  recurent_exp?: string;
  'ExtraData[silenturl]'?: string;
  'ExtraData[successurl]'?: string;
  'ExtraData[failedurl]'?: string;
  'ExtraData[backtosite]'?: string;
  'ExtraData[expireurl]'?: string;
  lang?: string;
};
